# organization name, it's used to get github repo url, also in page title
name: webdeps

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       Web Dependencies
description:
keywords:

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - deps-walk
 - rewrite-js-dependencies
 - deps-parse
 - postcss-parse-dependencies
 - deps-html
 - postcss-rename-dependencies
 - postcss-rm-imports
 - offset-source-map
 - apply-source-map
 - mnfy

# list of maintainers, this won't be sorted
maintainers:
 - name:    Jonathan Ong
   github:  jonathanong
   npm:     jongleberry
   twitter: jongleberry
   gittip:  jonathanong
   email:   me@jongleberry.com

   # if gravatar is attached to an email different from specified above,
   # add md5 of it here:
   avatar:  6e33cc0412b61cc01daac23c8989003c

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
